interval: 10 # Interval between pollings
loglevel: 4 # 1-5
concurrent_limit: 5
# Prometheus metrics are exposed at http://exporter_address/metrics
exporter_address: :8081

logstash:
   address: listener.logz.io:5050 # logstash sink. Lug will send all logs to this address
   additional_fields:
       token: "" # Additional fields sent to logstash server

# Address where JSON API will be served
json_api:
    address: :7001

repos:
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://rsync.chiark.greenend.org.uk/ftp/users/sgtatham/putty-website-mirror/
      interval: 3600
      path: /mnt/putty
      name: putty
    - type: shell_script
      name: archlinux-cn
      interval: 6000
      path: /mnt/archlinux-cn
      script: /worker-script/archlinux-cn.sh
      username: abc
      password: todo
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://rsync11.us.gentoo.org/gentoo-portage/
      interval: 3600
      path: /mnt/gentoo
      name: gentoo
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://ftp.ca.vim.org/vim
      interval: 3600
      path: /mnt/vim
      name: vim
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://ftp.tsukuba.wide.ad.jp/manjaro
      interval: 3600
      path: /mnt/manjaro
      name: manjaro
      exclude_hidden: true
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://rsync.alpinelinux.org/alpine/
      interval: 3600
      path: /mnt/alpine
      name: alpine
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://rsync.dante.ctan.org/CTAN	
      interval: 86400
      path: /mnt/ctan
      name: ctan
      exclude_hidden: true
    - type: shell_script
      script: /worker-script/rsync.sh
      source: cpan-rsync.perl.org::CPAN
      interval: 3600
      path: /mnt/cpan
      name: cpan
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://cran.csie.ntu.edu.tw/CRAN/CRAN/
      interval: 3600
      path: /mnt/cran
      name: cran
      ignore_vanish: true
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://mirrors.tuna.tsinghua.edu.cn/ctex/
      interval: 3600
      path: /mnt/ctex
      name: ctex
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://mirrors.ocf.berkeley.edu/gnu/
      interval: 43200
      path: /mnt/gnu
      name: gnu
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://mirror.steadfast.net/cygwin/
      interval: 3600
      path: /mnt/cygwin
      name: cygwin
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync.osuosl.org::ros-main
      interval: 3600
      path: /mnt/ros
      mirror_path: /mnt/ros/ubuntu
      name: ros
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://ftp.nluug.nl/kali/
      interval: 10800
      path: /mnt/kali
      name: kali
    - type: shell_script
      script: /worker-script/rsync.sh
      source: rsync://ftp.nluug.nl/kali-images/	
      interval: 10800
      path: /mnt/kali-images
      name: kali-images
    - type: shell_script
      script: /worker-script/bandersnatch.sh
      master: https://pypi.python.org/
      path: /mnt/pypi
      name: pypi
      interval: 3600
      retry_on_ssl_fail: true
    - type: shell_script
      script: /worker-script/anaconda.py
      path: /mnt/anaconda/
      name: anaconda
      interval: 3600
      thread_num: 80
      pkgs/main/linux-64: https://repo.continuum.io/pkgs/main/linux-64/
      pkgs/main/linux-32: https://repo.continuum.io/pkgs/main/linux-32/
      pkgs/main/linux-ppc64le: https://repo.continuum.io/pkgs/main/linux-ppc64le/
      pkgs/main/osx-64: https://repo.continuum.io/pkgs/main/osx-64/
      pkgs/main/win-64: https://repo.continuum.io/pkgs/main/win-64/
      pkgs/main/win-32: https://repo.continuum.io/pkgs/main/win-32/
      pkgs/main/noarch: https://repo.continuum.io/pkgs/main/noarch/
      pkgs/free/linux-64: https://repo.continuum.io/pkgs/free/linux-64/
      pkgs/free/linux-32: https://repo.continuum.io/pkgs/free/linux-32/
      pkgs/free/linux-armv6l: https://repo.continuum.io/pkgs/free/linux-armv6l/
      pkgs/free/linux-armv7l: https://repo.continuum.io/pkgs/free/linux-armv7l/
      pkgs/free/linux-ppc64le: https://repo.continuum.io/pkgs/free/linux-ppc64le/
      pkgs/free/osx-64: https://repo.continuum.io/pkgs/free/osx-64/
      pkgs/free/osx-32: https://repo.continuum.io/pkgs/free/osx-32/
      pkgs/free/win-64: https://repo.continuum.io/pkgs/free/win-64/
      pkgs/free/win-32: https://repo.continuum.io/pkgs/free/win-32/
      pkgs/free/noarch: https://repo.continuum.io/pkgs/free/noarch/
      pkgs/r/linux-64: https://repo.continuum.io/pkgs/r/linux-64/
      pkgs/r/linux-32: https://repo.continuum.io/pkgs/r/linux-32/
      pkgs/r/linux-armv6l: https://repo.continuum.io/pkgs/r/linux-armv6l/
      pkgs/r/linux-armv7l: https://repo.continuum.io/pkgs/r/linux-armv7l/
      pkgs/r/linux-ppc64le: https://repo.continuum.io/pkgs/r/linux-ppc64le/
      pkgs/r/osx-64: https://repo.continuum.io/pkgs/r/osx-64/
      pkgs/r/osx-32: https://repo.continuum.io/pkgs/r/osx-32/
      pkgs/r/win-64: https://repo.continuum.io/pkgs/r/win-64/
      pkgs/r/win-32: https://repo.continuum.io/pkgs/r/win-32/
      pkgs/r/noarch: https://repo.continuum.io/pkgs/r/noarch/
      pkgs/msys2/win-64: https://repo.continuum.io/pkgs/msys2/win-64/
      pkgs/msys2/win-32: https://repo.continuum.io/pkgs/msys2/win-32/
      cloud/conda-forge/noarch: https://conda.anaconda.org/conda-forge/noarch/
      cloud/conda-forge/linux-64: https://conda.anaconda.org/conda-forge/linux-64/
      cloud/conda-forge/osx-64: https://conda.anaconda.org/conda-forge/osx-64/
      cloud/conda-forge/win-64: https://conda.anaconda.org/conda-forge/win-64/
      cloud/bioconda/noarch: https://conda.anaconda.org/bioconda/noarch/
      cloud/bioconda/linux-64: https://conda.anaconda.org/bioconda/linux-64/
      cloud/bioconda/osx-64: https://conda.anaconda.org/bioconda/osx-64/
      cloud/pytorch/linux-64: https://conda.anaconda.org/pytorch/linux-64/
      cloud/pytorch/osx-64: https://conda.anaconda.org/pytorch/osx-64/
      cloud/pytorch/noarch: https://conda.anaconda.org/pytorch/noarch/
      cloud/pytorch/win-64: https://conda.anaconda.org/pytorch/win-64/
      cloud/ngsolve/noarch: https://conda.anaconda.org/ngsolve/noarch/
      cloud/ngsolve/linux-64: https://conda.anaconda.org/ngsolve/linux-64/
      cloud/ngsolve/osx-64: https://conda.anaconda.org/ngsolve/osx-64/
      cloud/ngsolve/win-64: https://conda.anaconda.org/ngsolve/win-64/
    - type: external
      name: rust-static
      proxy_to: https://static.rust-lang.org/
    - type: external
      name: debian-security
      proxy_to: http://ftp.sjtu.edu.cn/debian-security/
    - type: external
      name: centos
      proxy_to: http://ftp.sjtu.edu.cn/centos/
    - type: external
      name: ubuntu
      proxy_to: http://ftp.sjtu.edu.cn/ubuntu/
    - type: external
      name: archlinux
      proxy_to: http://ftp.sjtu.edu.cn/archlinux/
    - type: external
      name: fedora
      proxy_to: http://ftp.sjtu.edu.cn/fedora/
    - type: external
      name: debian
      proxy_to: http://ftp.sjtu.edu.cn/debian/
    - type: external
      name: ubuntu-cd
      proxy_to: http://ftp.sjtu.edu.cn/ubuntu-cd/
    - type: external
      name: debian-cd
      proxy_to: http://ftp.sjtu.edu.cn/debian-cd/
    - type: external
      name: linuxmint
      proxy_to: http://ftp.sjtu.edu.cn/linuxmint/
    - type: external
      name: deepin
      proxy_to: http://ftp.sjtu.edu.cn/deepin/
    - type: external
      name: opensuse
      proxy_to: http://ftp.sjtu.edu.cn/opensuse
    - type: external
      name: docker-registry
      proxy_to: https://registry-1.docker.io
      subdomain: docker
    - type: external
      name: npm-registry
      proxy_to: https://registry.npmjs.org
    - type: external
      name: flutter_infra
      proxy_to: https://storage.googleapis.com/flutter_infra/
    - type: external
      name: dart_packages
      proxy_to: https://pub.dartlang.org/
      subdomain: dart-pub
      filter_content_type: text/html.*
      filter_search_pattern: </footer>
      filter_replacement: "<div>dart-pub.mirrors.sjtug.sjtu.edu.cn is a reverse proxy of <a href='https://pub.dartlang.org/'>https://pub.dartlang.org/</a> provided by <a href=https://mirrors.sjtug.sjtu.edu.cn>SJTUG mirror service</a>.</footer>"
    - type: external
      name: maven-central
      proxy_to: http://repo.maven.apache.org/maven2/
    - type: shell_script
      script: /worker-script/git.sh
      name: git/homebrew-core.git
      origin: https://github.com/Homebrew/homebrew-core.git
      interval: 3801
      path: /mnt/git/homebrew-core.git
      no_direct_serving: true
    - type: shell_script
      script: /worker-script/git.sh
      name: git/homebrew-cask.git
      interval: 3801
      path: /mnt/git/homebrew-cask.git
      origin: https://github.com/Homebrew/homebrew-cask.git
      no_direct_serving: true
    - type: external
      name: homebrew-bottles
      proxy_to: https://homebrew.bintray.com/
      subdomain: homebrew-bottles
    - type: shell_script
      name: raspbian
      script: /worker-script/rsync.sh
      path: /mnt/raspbian
      interval: 10801
      source: rsync://archive.raspbian.org/archive/
    - type: shell_script
      name: raspberrypi
      script: /worker-script/rsync.sh
      path: /mnt/raspberrypi
      interval: 10801
      source: apt-repo.raspberrypi.org::archive
    - type: shell_script
      script: /worker-script/macports.sh
      source: rsync://rsync-origin.macports.org/macports/
      interval: 3600
      path: /mnt/macports
      name: macports
